---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-ops-view
  namespace: monitoring
  annotations:
    fluxcd.io/automated: 'true'
spec:
  releaseName: kube-ops-view
  helmVersion: v3
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: kube-ops-view
    version: 1.2.0
  values:
    image:
      repository: hjacobs/kube-ops-view
      tag: 20.4.0
    rbac:
      create: true
    ingress:
      enabled: true
      hostname: kube-ops-view.k8s
