apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: netdata
  namespace: monitoring
spec:
  releaseName: netdata
  helmVersion: v3
  chart:
    git: https://github.com/netdata/helmchart
    ref: master
    path: '.'
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: ''
        kubernetes.io/tls-acme: 'false'
      hosts:
        - netdata.k8s
