---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: flux
  helmVersion: v3
  chart:
    repository: https://charts.fluxcd.io/
    name: flux
    version: 1.5.0
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/devplayer0/gitops-test/master/k8s/flux/flux-values.yaml
