apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hostdev-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: hostdev-device-plugin
  template:
    metadata:
      labels:
        name: hostdev-device-plugin
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      priorityClassName: system-node-critical
      hostNetwork: true
      containers:
        - name: hostdev
          image: dtp263/k8s-hostdev-plugin
          args: ['--devs', '/dev/kvm:rwm']
          securityContext:
            privileged: true
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: dev
              mountPath: /dev
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev
          hostPath:
            path: /dev
