
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  helmVersion: v3
  chart:
    repository: https://charts.longhorn.io
    name: longhorn
    version: 1.0.2
  values:
    ingress:
      enabled: true
      host: longhorn.k8s
